[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/emotes"
  to = "/.netlify/functions/emotes"
  status = 200
[[redirects]]
  from = "/api/p-users"
  to = "premium_users.json"
  status = 200
